# Generated by Django 6.0.6 on 2026-07-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('tv', 'TV'), ('audio', 'Audio'), ('camera', 'Camera'), ('playstation', 'Playstation')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='banners/')),
                ('button1_text', models.CharField(max_length=100)),
                ('button2_text', models.CharField(max_length=100)),
                ('button1_link', models.CharField(blank=True, max_length=200)),
                ('button2_link', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
