# Generated by Django 6.0.6 on 2026-07-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
