# Generated by Django 6.0.6 on 2026-07-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_limited_edition_product_is_new_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
