# Generated by Django 6.0.6 on 2026-07-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_available_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('tv', 'TV'), ('audio', 'Audio'), ('camera', 'Camera'), ('gaming', 'Gaming'), ('laptop', 'Laptop'), ('accessories', 'Accessories')], max_length=30),
        ),
    ]
