# Generated by Django 6.0.6 on 2026-07-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productsection_remove_product_is_featured_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='section',
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.productsection'),
        ),
    ]
