# Generated by Django 6.0.6 on 2026-07-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_subcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='icon',
            field=models.CharField(default='cpu', max_length=100),
            preserve_default=False,
        ),
    ]
