# Generated by Django 6.0.6 on 2026-07-13 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productspecification_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button1_link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button1_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button2_link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button2_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='order',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
        migrations.AddField(
            model_name='banner',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='banner_posters/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='banner_videos/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('tv', 'TV'), ('audio', 'Audio'), ('camera', 'Camera'), ('gaming', 'Gaming'), ('laptop', 'Laptop'), ('accessories', 'Accessories')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='products.product'),
        ),
    ]
