# Generated by Django 6.0.6 on 2026-07-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_banner_alt_text_remove_banner_button1_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='video',
            field=models.FileField(upload_to='banner_videos/'),
        ),
    ]
