# Generated by Django 6.0.6 on 2026-07-31 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_address_address_type_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='date_of_birth',
            new_name='dob',
        ),
    ]
